# -*- coding: utf-8 -*-
"""customer_orders_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUse33G0RJNEmdXPNMuzMeXxc37vnYHN

# **Analyzing Customer Orders Using Python**

# **Situation**
You are working as a data analyst for an e-commerce company. Your task is to process and analyze customer orders to generate meaningful insights. Your company sells a variety of products across different categories, such as Electronics, Clothing, and Home Essentials. You need to determine which products are frequently purchased, classify customers based on their total spending, and analyze the most profitable product categories.

To achieve this, you will store, categorize, and analyze customer purchase data using Python's built-in data structures (lists, tuples, dictionaries, and sets) and control structures (loops and conditionals). The final output will help business managers make data-driven decisions regarding marketing strategies and inventory management.

# 1.	Store customer orders
•	Create a list of customer names
•	Store each customer's order details (customer name, product, price, category) as
tuples inside a list
•	Use a dictionary where keys are customer names and values are lists of ordered
products
"""

# CUSTOMER ORDERS PROJECT - Python Data Structures

# List of customers
customers = ["Amit", "Pooja", "Rahul", "Sneha", "Riya"]

# List of orders → (customer, product, price, category)

orders = [
    ("Amit", "Laptop", 750, "Electronics"),
    ("Amit", "Mouse", 20, "Electronics"),
    ("Pooja", "T-Shirt", 25, "Clothing"),
    ("Pooja", "Jeans", 45, "Clothing"),
    ("Rahul", "Mixer", 40, "Home Essentials"),
    ("Sneha", "Laptop", 750, "Electronics"),
    ("Sneha", "Dress", 60, "Clothing"),
    ("Riya", "Kettle", 30, "Home Essentials"),
    ("Riya", "Headphones", 50, "Electronics"),
]

"""# 2.	Classify products by category
•	Use a dictionary to map each product to its respective category
•	Create a set of unique product categories
•	Display all available product categories

"""

# Store customer → list of orders
customer_orders = {}

for order in orders:
    name, product, price, category = order

    if name not in customer_orders:
        customer_orders[name] = []

    customer_orders[name].append((product, price, category))

customer_orders

"""# 3.	Analyze customer orders
•	Use a loop to calculate the total amount each customer spends
•	If the total purchase value is above 100, classify the customer as a high-value buyer
•	If it is between 50 and 100, classify the customer as a moderate buyer
•	If it is below 50, classify them as a low-value buyer

"""

# Product categories
categories = set()
product_category = {}

for order in orders:
    product_category[order[1]] = order[3]
    categories.add(order[3])

categories

"""# 4.	Generate business insights
•	Calculate the total revenue per product category and store it in a dictionary
•	Extract unique products from all orders using a set
•	Use a list comprehension to find all customers who purchased electronics
•	Identify the top three highest-spending customers using sorting

"""

# Customer spending + classification

customer_total = {}
customer_type = {}

for name, items in customer_orders.items():
    total = sum(item[1] for item in items)
    customer_total[name] = total

    if total > 100:
        customer_type[name] = "High-Value Buyer"
    elif total >= 50:
        customer_type[name] = "Moderate Buyer"
    else:
        customer_type[name] = "Low-Value Buyer"

customer_total, customer_type

"""# 5.	Organize and display data
•	Print a summary of each customer’s total spending and their classification
•	Use set operations to find customers who purchased from multiple categories
•	Identify common customers who bought both electronics and clothing

"""

# Business Insights

# Revenue per category
category_revenue = {}

for order in orders:
    category = order[3]
    price = order[2]

    if category not in category_revenue:
        category_revenue[category] = 0

    category_revenue[category] += price

# Unique products
unique_products = {order[1] for order in orders}

# Customers who purchased electronics
electronics_customers = list({order[0] for order in orders if order[3] == "Electronics"})

# Top 3 customers
top_customers = sorted(customer_total.items(), key=lambda x: x[1], reverse=True)[:3]

category_revenue, unique_products, electronics_customers, top_customers

"""# Result
The final deliverable will be a detailed report summarizing customer classifications, total sales per category, and key insights about purchase behavior. This project demonstrates how Python’s data structures can be used to analyze real-world e-commerce data, helping businesses make informed decisions.
"""

# Final Report Output

print("===== CUSTOMER SUMMARY =====")
for name in customers:
    print(f"{name}: Total = ${customer_total[name]}, Type = {customer_type[name]}")

print("\n===== CATEGORY REVENUE =====")
for cat, rev in category_revenue.items():
    print(cat, "→ $", rev)

print("\n===== UNIQUE PRODUCTS =====")
print(unique_products)

print("\n===== ELECTRONICS BUYERS =====")
print(electronics_customers)

print("\n===== TOP 3 CUSTOMERS =====")
print(top_customers)